/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 6.9.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGraphicsView>
#include <QtWidgets/QGridLayout>
#include <QtWidgets/QLCDNumber>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QProgressBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QScrollBar>
#include <QtWidgets/QSlider>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QLabel *label;
    QLCDNumber *OSCLCD_Amp;
    QSlider *Slider_OSC_Hz;
    QSlider *Slider_OSC_Vol;
    QSlider *Slider_VCO_Hz;
    QSlider *Slider_VCO_vol;
    QLCDNumber *VCOLCD_Hz;
    QLCDNumber *FMOLCD_Amp;
    QSlider *Slider_FMO_Hz;
    QSlider *Slider_FMO_vol;
    QLCDNumber *VCOLCD_Amp;
    QLCDNumber *FMOLCD_Hz;
    QLabel *labelVCO;
    QLabel *labelFMO;
    QLabel *label_7;
    QLabel *label_8;
    QLabel *label_9;
    QFrame *frame;
    QCheckBox *cb_ssta1;
    QCheckBox *cb_ssta2;
    QCheckBox *cb_ssta3;
    QCheckBox *cb_ssta7;
    QCheckBox *cb_ssta4;
    QCheckBox *cb_ssta5;
    QCheckBox *cb_ssta0;
    QCheckBox *cb_ssta6;
    QFrame *frame_2;
    QSlider *Slider_mix_vol1;
    QSlider *Slider_mix_vol2;
    QSlider *Slider_mix_vol3;
    QSlider *Slider_mix_vol4;
    QSlider *Slider_mix_vol5;
    QSlider *Slider_mix_vol7;
    QSlider *Slider_mix_vol6;
    QSlider *Slider_mix_vol0;
    QFrame *frame_4;
    QCheckBox *cb_psta1;
    QCheckBox *cb_psta2;
    QCheckBox *cb_psta3;
    QCheckBox *cb_psta4;
    QCheckBox *cb_psta5;
    QCheckBox *cb_psta6;
    QCheckBox *cb_psta7;
    QCheckBox *cb_psta0;
    QPushButton *pB_Mute_StA;
    QLabel *label_2;
    QPushButton *pB_play_notes;
    QPushButton *pBtoggleRecord;
    QFrame *frame_5;
    QRadioButton *rb_S0;
    QRadioButton *rb_S1;
    QRadioButton *rb_S2;
    QRadioButton *rb_S3;
    QProgressBar *progressBar_record;
    QLCDNumber *OSCLCD_Hz;
    QLabel *glidefrequency;
    QPushButton *pB_Wavedisplay;
    QGraphicsView *oscilloscope_view;
    QPushButton *pB_wd_mode;
    QLabel *label_5;
    QPushButton *pB_Specrum;
    QFrame *frame_7;
    QLabel *wf_vco;
    QSpinBox *sB_VCO;
    QFrame *frame_8;
    QSpinBox *sB_OSC;
    QLabel *wf_OSC;
    QFrame *frame_9;
    QLabel *wf_fmo;
    QSpinBox *sB_FMO;
    QPushButton *pb_clear;
    QLabel *label_3;
    QLabel *label_10;
    QPushButton *pB_Mute;
    QWidget *layoutWidget;
    QGridLayout *gridLayout;
    QPushButton *pB_Rtsp;
    QComboBox *cB_Capture;
    QPushButton *pB_Save;
    QPushButton *pBAudioServer;
    QPushButton *pb_SDSview;
    QPushButton *pBGuiExit;
    QPushButton *pBComposer;
    QPushButton *pb_Keyboard;
    QCheckBox *cb_overwrite;
    QComboBox *cb_external;
    QComboBox *cb_bps;
    QProgressBar *Pbar_telapsed;
    QPushButton *pB_oscgroup;
    QPushButton *pb_fftmode;
    QLabel *lb_FMO_LFO;
    QLabel *lb_VCO_LFO;
    QSlider *SliderVCOadjust;
    QSlider *SliderFMOadjust;
    QLabel *label_6;
    QLabel *label_13;
    QLabel *glidefrequency_2;
    QCheckBox *cB_Combine;
    QSlider *Slider_slideFrq;
    QSlider *Slider_slideVol;
    QScrollBar *hs_hall_effect;
    QScrollBar *hs_balance;
    QLabel *label_14;
    QCheckBox *cb_connect_vcov;
    QCheckBox *cb_connect_fmov;
    QCheckBox *cb_connect_oscv;
    QCheckBox *cb_connect_oscf;
    QLabel *label_15;
    QLabel *label_16;
    QLabel *lbl_frqglide_sec;
    QPushButton *pBSynthesizer;
    QLabel *label_12;
    QFrame *frame_3;
    QCheckBox *cb_fsta0;
    QCheckBox *cb_fsta1;
    QCheckBox *cb_fsta2;
    QCheckBox *cb_fsta3;
    QCheckBox *cb_fsta4;
    QCheckBox *cb_fsta5;
    QCheckBox *cb_fsta7;
    QCheckBox *cb_fsta6;
    QLabel *label_17;
    QScrollBar *hs_chord_delay;
    QScrollBar *hs_pmw;
    QPushButton *pB_ADSR;
    QMenuBar *menubar;
    QMenu *menuSound_Lab_GUI;
    QMenu *menuIO;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName("MainWindow");
        MainWindow->resize(1207, 629);
        QPalette palette;
        QBrush brush(QColor(0, 0, 0, 255));
        brush.setStyle(Qt::BrushStyle::SolidPattern);
        palette.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::WindowText, brush);
        QBrush brush1(QColor(153, 193, 241, 255));
        brush1.setStyle(Qt::BrushStyle::SolidPattern);
        palette.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Button, brush1);
        QBrush brush2(QColor(255, 255, 255, 255));
        brush2.setStyle(Qt::BrushStyle::SolidPattern);
        palette.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Light, brush2);
        QBrush brush3(QColor(204, 224, 248, 255));
        brush3.setStyle(Qt::BrushStyle::SolidPattern);
        palette.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Midlight, brush3);
        QBrush brush4(QColor(76, 96, 120, 255));
        brush4.setStyle(Qt::BrushStyle::SolidPattern);
        palette.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Dark, brush4);
        QBrush brush5(QColor(102, 129, 161, 255));
        brush5.setStyle(Qt::BrushStyle::SolidPattern);
        palette.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Mid, brush5);
        palette.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Text, brush);
        palette.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::BrightText, brush2);
        palette.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::ButtonText, brush);
        palette.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Base, brush2);
        palette.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Window, brush1);
        palette.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::Shadow, brush);
        palette.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::AlternateBase, brush3);
        QBrush brush6(QColor(255, 255, 220, 255));
        brush6.setStyle(Qt::BrushStyle::SolidPattern);
        palette.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::ToolTipBase, brush6);
        palette.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::ToolTipText, brush);
        QBrush brush7(QColor(0, 0, 0, 127));
        brush7.setStyle(Qt::BrushStyle::SolidPattern);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette::ColorGroup::Active, QPalette::ColorRole::PlaceholderText, brush7);
#endif
        palette.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::WindowText, brush);
        QBrush brush8(QColor(239, 239, 239, 255));
        brush8.setStyle(Qt::BrushStyle::SolidPattern);
        palette.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Button, brush8);
        palette.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Light, brush2);
        QBrush brush9(QColor(202, 202, 202, 255));
        brush9.setStyle(Qt::BrushStyle::SolidPattern);
        palette.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Midlight, brush9);
        QBrush brush10(QColor(159, 159, 159, 255));
        brush10.setStyle(Qt::BrushStyle::SolidPattern);
        palette.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Dark, brush10);
        QBrush brush11(QColor(184, 184, 184, 255));
        brush11.setStyle(Qt::BrushStyle::SolidPattern);
        palette.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Mid, brush11);
        palette.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Text, brush);
        palette.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::BrightText, brush2);
        palette.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::ButtonText, brush);
        palette.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Base, brush2);
        palette.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Window, brush8);
        QBrush brush12(QColor(118, 118, 118, 255));
        brush12.setStyle(Qt::BrushStyle::SolidPattern);
        palette.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::Shadow, brush12);
        QBrush brush13(QColor(247, 247, 247, 255));
        brush13.setStyle(Qt::BrushStyle::SolidPattern);
        palette.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::AlternateBase, brush13);
        palette.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::ToolTipBase, brush6);
        palette.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::ToolTipText, brush);
        QBrush brush14(QColor(0, 0, 0, 128));
        brush14.setStyle(Qt::BrushStyle::SolidPattern);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette::ColorGroup::Inactive, QPalette::ColorRole::PlaceholderText, brush14);
#endif
        palette.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::WindowText, brush4);
        palette.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Button, brush1);
        palette.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Light, brush2);
        palette.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Midlight, brush3);
        palette.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Dark, brush4);
        palette.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Mid, brush5);
        palette.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Text, brush4);
        palette.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::BrightText, brush2);
        palette.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::ButtonText, brush4);
        palette.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Base, brush1);
        palette.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Window, brush1);
        QBrush brush15(QColor(177, 177, 177, 255));
        brush15.setStyle(Qt::BrushStyle::SolidPattern);
        palette.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::Shadow, brush15);
        palette.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::AlternateBase, brush13);
        palette.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::ToolTipBase, brush6);
        palette.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::ToolTipText, brush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette::ColorGroup::Disabled, QPalette::ColorRole::PlaceholderText, brush14);
#endif
        MainWindow->setPalette(palette);
        MainWindow->setAcceptDrops(false);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName("centralwidget");
        label = new QLabel(centralwidget);
        label->setObjectName("label");
        label->setGeometry(QRect(220, 10, 41, 41));
        label->setWordWrap(true);
        OSCLCD_Amp = new QLCDNumber(centralwidget);
        OSCLCD_Amp->setObjectName("OSCLCD_Amp");
        OSCLCD_Amp->setGeometry(QRect(330, 10, 111, 51));
        Slider_OSC_Hz = new QSlider(centralwidget);
        Slider_OSC_Hz->setObjectName("Slider_OSC_Hz");
        Slider_OSC_Hz->setGeometry(QRect(210, 10, 16, 160));
        Slider_OSC_Hz->setMinimum(1);
        Slider_OSC_Hz->setMaximum(72);
        Slider_OSC_Hz->setPageStep(12);
        Slider_OSC_Hz->setOrientation(Qt::Orientation::Vertical);
        Slider_OSC_Hz->setTickPosition(QSlider::TickPosition::TicksAbove);
        Slider_OSC_Hz->setTickInterval(12);
        Slider_OSC_Vol = new QSlider(centralwidget);
        Slider_OSC_Vol->setObjectName("Slider_OSC_Vol");
        Slider_OSC_Vol->setGeometry(QRect(290, 10, 16, 160));
        Slider_OSC_Vol->setMaximum(100);
        Slider_OSC_Vol->setOrientation(Qt::Orientation::Vertical);
        Slider_VCO_Hz = new QSlider(centralwidget);
        Slider_VCO_Hz->setObjectName("Slider_VCO_Hz");
        Slider_VCO_Hz->setGeometry(QRect(210, 190, 16, 160));
        Slider_VCO_Hz->setMinimum(1);
        Slider_VCO_Hz->setMaximum(72);
        Slider_VCO_Hz->setSingleStep(1);
        Slider_VCO_Hz->setPageStep(12);
        Slider_VCO_Hz->setOrientation(Qt::Orientation::Vertical);
        Slider_VCO_vol = new QSlider(centralwidget);
        Slider_VCO_vol->setObjectName("Slider_VCO_vol");
        Slider_VCO_vol->setGeometry(QRect(290, 190, 16, 160));
        Slider_VCO_vol->setMaximum(100);
        Slider_VCO_vol->setOrientation(Qt::Orientation::Vertical);
        VCOLCD_Hz = new QLCDNumber(centralwidget);
        VCOLCD_Hz->setObjectName("VCOLCD_Hz");
        VCOLCD_Hz->setGeometry(QRect(60, 190, 131, 51));
        VCOLCD_Hz->setDigitCount(5);
        FMOLCD_Amp = new QLCDNumber(centralwidget);
        FMOLCD_Amp->setObjectName("FMOLCD_Amp");
        FMOLCD_Amp->setGeometry(QRect(330, 380, 111, 51));
        Slider_FMO_Hz = new QSlider(centralwidget);
        Slider_FMO_Hz->setObjectName("Slider_FMO_Hz");
        Slider_FMO_Hz->setGeometry(QRect(210, 380, 16, 160));
        Slider_FMO_Hz->setMinimum(1);
        Slider_FMO_Hz->setMaximum(72);
        Slider_FMO_Hz->setSingleStep(1);
        Slider_FMO_Hz->setPageStep(12);
        Slider_FMO_Hz->setOrientation(Qt::Orientation::Vertical);
        Slider_FMO_vol = new QSlider(centralwidget);
        Slider_FMO_vol->setObjectName("Slider_FMO_vol");
        Slider_FMO_vol->setGeometry(QRect(290, 380, 16, 160));
        Slider_FMO_vol->setMaximum(100);
        Slider_FMO_vol->setOrientation(Qt::Orientation::Vertical);
        VCOLCD_Amp = new QLCDNumber(centralwidget);
        VCOLCD_Amp->setObjectName("VCOLCD_Amp");
        VCOLCD_Amp->setGeometry(QRect(330, 190, 111, 51));
        FMOLCD_Hz = new QLCDNumber(centralwidget);
        FMOLCD_Hz->setObjectName("FMOLCD_Hz");
        FMOLCD_Hz->setGeometry(QRect(60, 380, 131, 51));
        FMOLCD_Hz->setDigitCount(5);
        labelVCO = new QLabel(centralwidget);
        labelVCO->setObjectName("labelVCO");
        labelVCO->setGeometry(QRect(240, 190, 31, 17));
        labelFMO = new QLabel(centralwidget);
        labelFMO->setObjectName("labelFMO");
        labelFMO->setGeometry(QRect(240, 380, 31, 17));
        label_7 = new QLabel(centralwidget);
        label_7->setObjectName("label_7");
        label_7->setGeometry(QRect(60, 430, 111, 20));
        label_8 = new QLabel(centralwidget);
        label_8->setObjectName("label_8");
        label_8->setGeometry(QRect(60, 240, 111, 20));
        label_9 = new QLabel(centralwidget);
        label_9->setObjectName("label_9");
        label_9->setGeometry(QRect(60, 60, 111, 20));
        frame = new QFrame(centralwidget);
        frame->setObjectName("frame");
        frame->setGeometry(QRect(960, 40, 90, 251));
        frame->setFrameShape(QFrame::Shape::StyledPanel);
        frame->setFrameShadow(QFrame::Shadow::Raised);
        cb_ssta1 = new QCheckBox(frame);
        cb_ssta1->setObjectName("cb_ssta1");
        cb_ssta1->setGeometry(QRect(0, 40, 80, 23));
        cb_ssta2 = new QCheckBox(frame);
        cb_ssta2->setObjectName("cb_ssta2");
        cb_ssta2->setGeometry(QRect(0, 70, 80, 23));
        cb_ssta3 = new QCheckBox(frame);
        cb_ssta3->setObjectName("cb_ssta3");
        cb_ssta3->setGeometry(QRect(0, 100, 80, 23));
        cb_ssta7 = new QCheckBox(frame);
        cb_ssta7->setObjectName("cb_ssta7");
        cb_ssta7->setGeometry(QRect(0, 190, 80, 23));
        cb_ssta4 = new QCheckBox(frame);
        cb_ssta4->setObjectName("cb_ssta4");
        cb_ssta4->setGeometry(QRect(0, 130, 80, 23));
        cb_ssta5 = new QCheckBox(frame);
        cb_ssta5->setObjectName("cb_ssta5");
        cb_ssta5->setGeometry(QRect(0, 160, 80, 23));
        cb_ssta0 = new QCheckBox(frame);
        cb_ssta0->setObjectName("cb_ssta0");
        cb_ssta0->setGeometry(QRect(0, 10, 80, 23));
        cb_ssta6 = new QCheckBox(frame);
        cb_ssta6->setObjectName("cb_ssta6");
        cb_ssta6->setGeometry(QRect(0, 220, 80, 23));
        frame_2 = new QFrame(centralwidget);
        frame_2->setObjectName("frame_2");
        frame_2->setGeometry(QRect(760, 40, 191, 251));
        frame_2->setFrameShape(QFrame::Shape::StyledPanel);
        frame_2->setFrameShadow(QFrame::Shadow::Raised);
        Slider_mix_vol1 = new QSlider(frame_2);
        Slider_mix_vol1->setObjectName("Slider_mix_vol1");
        Slider_mix_vol1->setGeometry(QRect(0, 40, 160, 16));
        Slider_mix_vol1->setMaximum(100);
        Slider_mix_vol1->setOrientation(Qt::Orientation::Horizontal);
        Slider_mix_vol2 = new QSlider(frame_2);
        Slider_mix_vol2->setObjectName("Slider_mix_vol2");
        Slider_mix_vol2->setGeometry(QRect(0, 70, 160, 16));
        Slider_mix_vol2->setMaximum(100);
        Slider_mix_vol2->setOrientation(Qt::Orientation::Horizontal);
        Slider_mix_vol3 = new QSlider(frame_2);
        Slider_mix_vol3->setObjectName("Slider_mix_vol3");
        Slider_mix_vol3->setGeometry(QRect(0, 100, 160, 16));
        Slider_mix_vol3->setMaximum(100);
        Slider_mix_vol3->setOrientation(Qt::Orientation::Horizontal);
        Slider_mix_vol4 = new QSlider(frame_2);
        Slider_mix_vol4->setObjectName("Slider_mix_vol4");
        Slider_mix_vol4->setGeometry(QRect(0, 130, 160, 16));
        Slider_mix_vol4->setMaximum(100);
        Slider_mix_vol4->setOrientation(Qt::Orientation::Horizontal);
        Slider_mix_vol5 = new QSlider(frame_2);
        Slider_mix_vol5->setObjectName("Slider_mix_vol5");
        Slider_mix_vol5->setGeometry(QRect(0, 160, 160, 16));
        Slider_mix_vol5->setMaximum(100);
        Slider_mix_vol5->setOrientation(Qt::Orientation::Horizontal);
        Slider_mix_vol7 = new QSlider(frame_2);
        Slider_mix_vol7->setObjectName("Slider_mix_vol7");
        Slider_mix_vol7->setGeometry(QRect(0, 190, 160, 16));
        Slider_mix_vol7->setMaximum(100);
        Slider_mix_vol7->setOrientation(Qt::Orientation::Horizontal);
        Slider_mix_vol6 = new QSlider(frame_2);
        Slider_mix_vol6->setObjectName("Slider_mix_vol6");
        Slider_mix_vol6->setGeometry(QRect(0, 220, 160, 16));
        Slider_mix_vol6->setMaximum(100);
        Slider_mix_vol6->setOrientation(Qt::Orientation::Horizontal);
        Slider_mix_vol0 = new QSlider(frame_2);
        Slider_mix_vol0->setObjectName("Slider_mix_vol0");
        Slider_mix_vol0->setGeometry(QRect(0, 10, 160, 16));
        Slider_mix_vol0->setMaximum(100);
        Slider_mix_vol0->setOrientation(Qt::Orientation::Horizontal);
        frame_4 = new QFrame(centralwidget);
        frame_4->setObjectName("frame_4");
        frame_4->setGeometry(QRect(1140, 40, 40, 251));
        frame_4->setFrameShape(QFrame::Shape::StyledPanel);
        frame_4->setFrameShadow(QFrame::Shadow::Raised);
        cb_psta1 = new QCheckBox(frame_4);
        cb_psta1->setObjectName("cb_psta1");
        cb_psta1->setGeometry(QRect(0, 40, 92, 23));
        cb_psta2 = new QCheckBox(frame_4);
        cb_psta2->setObjectName("cb_psta2");
        cb_psta2->setGeometry(QRect(0, 70, 92, 23));
        cb_psta3 = new QCheckBox(frame_4);
        cb_psta3->setObjectName("cb_psta3");
        cb_psta3->setGeometry(QRect(0, 100, 92, 23));
        cb_psta4 = new QCheckBox(frame_4);
        cb_psta4->setObjectName("cb_psta4");
        cb_psta4->setGeometry(QRect(0, 130, 92, 23));
        cb_psta5 = new QCheckBox(frame_4);
        cb_psta5->setObjectName("cb_psta5");
        cb_psta5->setGeometry(QRect(0, 160, 92, 23));
        cb_psta6 = new QCheckBox(frame_4);
        cb_psta6->setObjectName("cb_psta6");
        cb_psta6->setGeometry(QRect(0, 220, 92, 23));
        cb_psta7 = new QCheckBox(frame_4);
        cb_psta7->setObjectName("cb_psta7");
        cb_psta7->setGeometry(QRect(0, 190, 92, 23));
        cb_psta0 = new QCheckBox(frame_4);
        cb_psta0->setObjectName("cb_psta0");
        cb_psta0->setGeometry(QRect(0, 10, 92, 23));
        pB_Mute_StA = new QPushButton(centralwidget);
        pB_Mute_StA->setObjectName("pB_Mute_StA");
        pB_Mute_StA->setGeometry(QRect(1110, 290, 75, 25));
        label_2 = new QLabel(centralwidget);
        label_2->setObjectName("label_2");
        label_2->setGeometry(QRect(480, 140, 50, 17));
        pB_play_notes = new QPushButton(centralwidget);
        pB_play_notes->setObjectName("pB_play_notes");
        pB_play_notes->setGeometry(QRect(480, 10, 89, 41));
        pBtoggleRecord = new QPushButton(centralwidget);
        pBtoggleRecord->setObjectName("pBtoggleRecord");
        pBtoggleRecord->setGeometry(QRect(470, 470, 89, 25));
        frame_5 = new QFrame(centralwidget);
        frame_5->setObjectName("frame_5");
        frame_5->setGeometry(QRect(1000, 370, 151, 121));
        frame_5->setFrameShape(QFrame::Shape::StyledPanel);
        frame_5->setFrameShadow(QFrame::Shadow::Raised);
        rb_S0 = new QRadioButton(frame_5);
        rb_S0->setObjectName("rb_S0");
        rb_S0->setGeometry(QRect(20, 0, 111, 23));
        rb_S1 = new QRadioButton(frame_5);
        rb_S1->setObjectName("rb_S1");
        rb_S1->setGeometry(QRect(20, 30, 111, 23));
        rb_S2 = new QRadioButton(frame_5);
        rb_S2->setObjectName("rb_S2");
        rb_S2->setGeometry(QRect(20, 60, 111, 23));
        rb_S3 = new QRadioButton(frame_5);
        rb_S3->setObjectName("rb_S3");
        rb_S3->setGeometry(QRect(20, 90, 121, 23));
        progressBar_record = new QProgressBar(centralwidget);
        progressBar_record->setObjectName("progressBar_record");
        progressBar_record->setGeometry(QRect(580, 470, 411, 23));
        progressBar_record->setValue(0);
        OSCLCD_Hz = new QLCDNumber(centralwidget);
        OSCLCD_Hz->setObjectName("OSCLCD_Hz");
        OSCLCD_Hz->setGeometry(QRect(60, 10, 141, 51));
        OSCLCD_Hz->setDigitCount(5);
        OSCLCD_Hz->setProperty("value", QVariant(0.000000000000000));
        glidefrequency = new QLabel(centralwidget);
        glidefrequency->setObjectName("glidefrequency");
        glidefrequency->setGeometry(QRect(0, 140, 41, 41));
        glidefrequency->setWordWrap(true);
        pB_Wavedisplay = new QPushButton(centralwidget);
        pB_Wavedisplay->setObjectName("pB_Wavedisplay");
        pB_Wavedisplay->setGeometry(QRect(480, 260, 81, 25));
        oscilloscope_view = new QGraphicsView(centralwidget);
        oscilloscope_view->setObjectName("oscilloscope_view");
        oscilloscope_view->setGeometry(QRect(480, 290, 512, 166));
        oscilloscope_view->setFrameShape(QFrame::Shape::Box);
        oscilloscope_view->setLineWidth(2);
        pB_wd_mode = new QPushButton(centralwidget);
        pB_wd_mode->setObjectName("pB_wd_mode");
        pB_wd_mode->setGeometry(QRect(570, 260, 81, 25));
        label_5 = new QLabel(centralwidget);
        label_5->setObjectName("label_5");
        label_5->setGeometry(QRect(480, 80, 50, 17));
        pB_Specrum = new QPushButton(centralwidget);
        pB_Specrum->setObjectName("pB_Specrum");
        pB_Specrum->setGeometry(QRect(570, 10, 88, 25));
        frame_7 = new QFrame(centralwidget);
        frame_7->setObjectName("frame_7");
        frame_7->setGeometry(QRect(60, 270, 131, 41));
        frame_7->setFrameShape(QFrame::Shape::StyledPanel);
        frame_7->setFrameShadow(QFrame::Shadow::Raised);
        wf_vco = new QLabel(frame_7);
        wf_vco->setObjectName("wf_vco");
        wf_vco->setGeometry(QRect(0, 10, 66, 17));
        sB_VCO = new QSpinBox(frame_7);
        sB_VCO->setObjectName("sB_VCO");
        sB_VCO->setGeometry(QRect(90, 0, 44, 41));
        sB_VCO->setWrapping(true);
        sB_VCO->setMaximum(9);
        frame_8 = new QFrame(centralwidget);
        frame_8->setObjectName("frame_8");
        frame_8->setGeometry(QRect(60, 90, 131, 41));
        frame_8->setFrameShape(QFrame::Shape::StyledPanel);
        frame_8->setFrameShadow(QFrame::Shadow::Raised);
        sB_OSC = new QSpinBox(frame_8);
        sB_OSC->setObjectName("sB_OSC");
        sB_OSC->setGeometry(QRect(90, 0, 44, 41));
        sB_OSC->setWrapping(true);
        sB_OSC->setMaximum(9);
        wf_OSC = new QLabel(frame_8);
        wf_OSC->setObjectName("wf_OSC");
        wf_OSC->setGeometry(QRect(0, 10, 66, 17));
        frame_9 = new QFrame(centralwidget);
        frame_9->setObjectName("frame_9");
        frame_9->setGeometry(QRect(60, 460, 131, 41));
        frame_9->setFrameShape(QFrame::Shape::StyledPanel);
        frame_9->setFrameShadow(QFrame::Shadow::Raised);
        wf_fmo = new QLabel(frame_9);
        wf_fmo->setObjectName("wf_fmo");
        wf_fmo->setGeometry(QRect(0, 10, 66, 17));
        sB_FMO = new QSpinBox(frame_9);
        sB_FMO->setObjectName("sB_FMO");
        sB_FMO->setGeometry(QRect(90, 0, 44, 41));
        sB_FMO->setWrapping(true);
        sB_FMO->setMaximum(9);
        pb_clear = new QPushButton(centralwidget);
        pb_clear->setObjectName("pb_clear");
        pb_clear->setGeometry(QRect(1030, 290, 75, 25));
        label_3 = new QLabel(centralwidget);
        label_3->setObjectName("label_3");
        label_3->setGeometry(QRect(480, 200, 81, 31));
        label_3->setWordWrap(true);
        label_10 = new QLabel(centralwidget);
        label_10->setObjectName("label_10");
        label_10->setGeometry(QRect(310, 20, 16, 131));
        label_10->setTextFormat(Qt::TextFormat::PlainText);
        label_10->setWordWrap(true);
        pB_Mute = new QPushButton(centralwidget);
        pB_Mute->setObjectName("pB_Mute");
        pB_Mute->setGeometry(QRect(330, 80, 88, 25));
        layoutWidget = new QWidget(centralwidget);
        layoutWidget->setObjectName("layoutWidget");
        layoutWidget->setGeometry(QRect(470, 500, 661, 71));
        gridLayout = new QGridLayout(layoutWidget);
        gridLayout->setObjectName("gridLayout");
        gridLayout->setSizeConstraint(QLayout::SizeConstraint::SetMinimumSize);
        gridLayout->setHorizontalSpacing(15);
        gridLayout->setVerticalSpacing(6);
        gridLayout->setContentsMargins(0, 0, 0, 0);
        pB_Rtsp = new QPushButton(layoutWidget);
        pB_Rtsp->setObjectName("pB_Rtsp");

        gridLayout->addWidget(pB_Rtsp, 0, 1, 1, 1);

        cB_Capture = new QComboBox(layoutWidget);
        cB_Capture->setObjectName("cB_Capture");

        gridLayout->addWidget(cB_Capture, 1, 2, 1, 1);

        pB_Save = new QPushButton(layoutWidget);
        pB_Save->setObjectName("pB_Save");

        gridLayout->addWidget(pB_Save, 0, 3, 1, 1);

        pBAudioServer = new QPushButton(layoutWidget);
        pBAudioServer->setObjectName("pBAudioServer");

        gridLayout->addWidget(pBAudioServer, 1, 4, 1, 1);

        pb_SDSview = new QPushButton(layoutWidget);
        pb_SDSview->setObjectName("pb_SDSview");

        gridLayout->addWidget(pb_SDSview, 1, 1, 1, 1);

        pBGuiExit = new QPushButton(layoutWidget);
        pBGuiExit->setObjectName("pBGuiExit");

        gridLayout->addWidget(pBGuiExit, 1, 3, 1, 1);

        pBComposer = new QPushButton(layoutWidget);
        pBComposer->setObjectName("pBComposer");

        gridLayout->addWidget(pBComposer, 0, 2, 1, 1);

        pb_Keyboard = new QPushButton(layoutWidget);
        pb_Keyboard->setObjectName("pb_Keyboard");

        gridLayout->addWidget(pb_Keyboard, 0, 4, 1, 1);

        cb_overwrite = new QCheckBox(layoutWidget);
        cb_overwrite->setObjectName("cb_overwrite");

        gridLayout->addWidget(cb_overwrite, 1, 0, 1, 1);

        cb_external = new QComboBox(layoutWidget);
        cb_external->setObjectName("cb_external");
        cb_external->setEditable(false);

        gridLayout->addWidget(cb_external, 0, 0, 1, 1);

        cb_bps = new QComboBox(centralwidget);
        cb_bps->setObjectName("cb_bps");
        cb_bps->setGeometry(QRect(540, 200, 71, 25));
        Pbar_telapsed = new QProgressBar(centralwidget);
        Pbar_telapsed->setObjectName("Pbar_telapsed");
        Pbar_telapsed->setGeometry(QRect(451, 290, 20, 161));
        Pbar_telapsed->setValue(24);
        Pbar_telapsed->setTextVisible(true);
        Pbar_telapsed->setOrientation(Qt::Orientation::Vertical);
        pB_oscgroup = new QPushButton(centralwidget);
        pB_oscgroup->setObjectName("pB_oscgroup");
        pB_oscgroup->setGeometry(QRect(660, 260, 81, 26));
        pb_fftmode = new QPushButton(centralwidget);
        pb_fftmode->setObjectName("pb_fftmode");
        pb_fftmode->setGeometry(QRect(660, 230, 81, 26));
        lb_FMO_LFO = new QLabel(centralwidget);
        lb_FMO_LFO->setObjectName("lb_FMO_LFO");
        lb_FMO_LFO->setGeometry(QRect(220, 400, 31, 18));
        lb_VCO_LFO = new QLabel(centralwidget);
        lb_VCO_LFO->setObjectName("lb_VCO_LFO");
        lb_VCO_LFO->setGeometry(QRect(220, 210, 31, 18));
        SliderVCOadjust = new QSlider(centralwidget);
        SliderVCOadjust->setObjectName("SliderVCOadjust");
        SliderVCOadjust->setGeometry(QRect(40, 190, 16, 160));
        SliderVCOadjust->setMaximum(50);
        SliderVCOadjust->setOrientation(Qt::Orientation::Vertical);
        SliderFMOadjust = new QSlider(centralwidget);
        SliderFMOadjust->setObjectName("SliderFMOadjust");
        SliderFMOadjust->setGeometry(QRect(40, 380, 16, 160));
        SliderFMOadjust->setMaximum(50);
        SliderFMOadjust->setOrientation(Qt::Orientation::Vertical);
        label_6 = new QLabel(centralwidget);
        label_6->setObjectName("label_6");
        label_6->setGeometry(QRect(30, 540, 66, 18));
        label_13 = new QLabel(centralwidget);
        label_13->setObjectName("label_13");
        label_13->setGeometry(QRect(30, 350, 66, 18));
        glidefrequency_2 = new QLabel(centralwidget);
        glidefrequency_2->setObjectName("glidefrequency_2");
        glidefrequency_2->setGeometry(QRect(240, 140, 41, 31));
        glidefrequency_2->setWordWrap(true);
        cB_Combine = new QCheckBox(centralwidget);
        cB_Combine->setObjectName("cB_Combine");
        cB_Combine->setGeometry(QRect(100, 150, 92, 24));
        cB_Combine->setLayoutDirection(Qt::LayoutDirection::RightToLeft);
        Slider_slideFrq = new QSlider(centralwidget);
        Slider_slideFrq->setObjectName("Slider_slideFrq");
        Slider_slideFrq->setGeometry(QRect(40, 10, 16, 160));
        Slider_slideFrq->setMinimum(0);
        Slider_slideFrq->setMaximum(100);
        Slider_slideFrq->setPageStep(10);
        Slider_slideFrq->setValue(0);
        Slider_slideFrq->setOrientation(Qt::Orientation::Vertical);
        Slider_slideVol = new QSlider(centralwidget);
        Slider_slideVol->setObjectName("Slider_slideVol");
        Slider_slideVol->setGeometry(QRect(270, 10, 16, 160));
        Slider_slideVol->setMaximum(100);
        Slider_slideVol->setOrientation(Qt::Orientation::Vertical);
        hs_hall_effect = new QScrollBar(centralwidget);
        hs_hall_effect->setObjectName("hs_hall_effect");
        hs_hall_effect->setGeometry(QRect(540, 80, 160, 16));
        hs_hall_effect->setMaximum(100);
        hs_hall_effect->setPageStep(1);
        hs_hall_effect->setOrientation(Qt::Orientation::Horizontal);
        hs_hall_effect->setInvertedControls(false);
        hs_balance = new QScrollBar(centralwidget);
        hs_balance->setObjectName("hs_balance");
        hs_balance->setGeometry(QRect(540, 110, 160, 16));
        hs_balance->setMinimum(-100);
        hs_balance->setMaximum(100);
        hs_balance->setPageStep(1);
        hs_balance->setOrientation(Qt::Orientation::Horizontal);
        hs_balance->setInvertedControls(false);
        label_14 = new QLabel(centralwidget);
        label_14->setObjectName("label_14");
        label_14->setGeometry(QRect(480, 110, 50, 17));
        cb_connect_vcov = new QCheckBox(centralwidget);
        cb_connect_vcov->setObjectName("cb_connect_vcov");
        cb_connect_vcov->setGeometry(QRect(330, 460, 111, 24));
        cb_connect_fmov = new QCheckBox(centralwidget);
        cb_connect_fmov->setObjectName("cb_connect_fmov");
        cb_connect_fmov->setGeometry(QRect(330, 270, 111, 24));
        cb_connect_oscv = new QCheckBox(centralwidget);
        cb_connect_oscv->setObjectName("cb_connect_oscv");
        cb_connect_oscv->setGeometry(QRect(330, 150, 111, 24));
        cb_connect_oscf = new QCheckBox(centralwidget);
        cb_connect_oscf->setObjectName("cb_connect_oscf");
        cb_connect_oscf->setGeometry(QRect(330, 120, 111, 24));
        label_15 = new QLabel(centralwidget);
        label_15->setObjectName("label_15");
        label_15->setGeometry(QRect(330, 240, 111, 20));
        label_16 = new QLabel(centralwidget);
        label_16->setObjectName("label_16");
        label_16->setGeometry(QRect(330, 430, 111, 20));
        lbl_frqglide_sec = new QLabel(centralwidget);
        lbl_frqglide_sec->setObjectName("lbl_frqglide_sec");
        lbl_frqglide_sec->setGeometry(QRect(10, 70, 40, 41));
        pBSynthesizer = new QPushButton(centralwidget);
        pBSynthesizer->setObjectName("pBSynthesizer");
        pBSynthesizer->setGeometry(QRect(1010, 330, 121, 26));
        label_12 = new QLabel(centralwidget);
        label_12->setObjectName("label_12");
        label_12->setGeometry(QRect(765, 10, 421, 20));
        frame_3 = new QFrame(centralwidget);
        frame_3->setObjectName("frame_3");
        frame_3->setGeometry(QRect(1050, 40, 40, 251));
        frame_3->setFrameShape(QFrame::Shape::StyledPanel);
        frame_3->setFrameShadow(QFrame::Shadow::Raised);
        cb_fsta0 = new QCheckBox(frame_3);
        cb_fsta0->setObjectName("cb_fsta0");
        cb_fsta0->setGeometry(QRect(10, 10, 40, 24));
        cb_fsta0->setCheckable(true);
        cb_fsta1 = new QCheckBox(frame_3);
        cb_fsta1->setObjectName("cb_fsta1");
        cb_fsta1->setGeometry(QRect(10, 40, 40, 24));
        cb_fsta1->setCheckable(true);
        cb_fsta2 = new QCheckBox(frame_3);
        cb_fsta2->setObjectName("cb_fsta2");
        cb_fsta2->setGeometry(QRect(10, 70, 40, 24));
        cb_fsta2->setCheckable(true);
        cb_fsta3 = new QCheckBox(frame_3);
        cb_fsta3->setObjectName("cb_fsta3");
        cb_fsta3->setGeometry(QRect(10, 100, 40, 24));
        cb_fsta3->setCheckable(true);
        cb_fsta4 = new QCheckBox(frame_3);
        cb_fsta4->setObjectName("cb_fsta4");
        cb_fsta4->setGeometry(QRect(10, 130, 40, 24));
        cb_fsta4->setCheckable(true);
        cb_fsta5 = new QCheckBox(frame_3);
        cb_fsta5->setObjectName("cb_fsta5");
        cb_fsta5->setGeometry(QRect(10, 160, 40, 24));
        cb_fsta5->setCheckable(true);
        cb_fsta7 = new QCheckBox(frame_3);
        cb_fsta7->setObjectName("cb_fsta7");
        cb_fsta7->setGeometry(QRect(10, 190, 40, 24));
        cb_fsta7->setCheckable(true);
        cb_fsta6 = new QCheckBox(frame_3);
        cb_fsta6->setObjectName("cb_fsta6");
        cb_fsta6->setGeometry(QRect(10, 220, 40, 24));
        cb_fsta6->setCheckable(true);
        label_17 = new QLabel(centralwidget);
        label_17->setObjectName("label_17");
        label_17->setGeometry(QRect(480, 170, 50, 17));
        hs_chord_delay = new QScrollBar(centralwidget);
        hs_chord_delay->setObjectName("hs_chord_delay");
        hs_chord_delay->setGeometry(QRect(540, 170, 160, 16));
        hs_chord_delay->setMinimum(0);
        hs_chord_delay->setMaximum(200);
        hs_chord_delay->setPageStep(1);
        hs_chord_delay->setOrientation(Qt::Orientation::Horizontal);
        hs_chord_delay->setInvertedControls(false);
        hs_pmw = new QScrollBar(centralwidget);
        hs_pmw->setObjectName("hs_pmw");
        hs_pmw->setGeometry(QRect(540, 140, 160, 16));
        hs_pmw->setMinimum(0);
        hs_pmw->setMaximum(100);
        hs_pmw->setPageStep(1);
        hs_pmw->setOrientation(Qt::Orientation::Horizontal);
        hs_pmw->setInvertedControls(false);
        pB_ADSR = new QPushButton(centralwidget);
        pB_ADSR->setObjectName("pB_ADSR");
        pB_ADSR->setGeometry(QRect(660, 10, 88, 25));
        MainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName("menubar");
        menubar->setGeometry(QRect(0, 0, 1207, 23));
        menuSound_Lab_GUI = new QMenu(menubar);
        menuSound_Lab_GUI->setObjectName("menuSound_Lab_GUI");
        menuIO = new QMenu(menubar);
        menuIO->setObjectName("menuIO");
        MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName("statusbar");
        MainWindow->setStatusBar(statusbar);

        menubar->addAction(menuSound_Lab_GUI->menuAction());
        menubar->addAction(menuIO->menuAction());

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "Ocean", nullptr));
        label->setText(QCoreApplication::translate("MainWindow", "OSC (main)", nullptr));
        labelVCO->setText(QCoreApplication::translate("MainWindow", "VCO", nullptr));
        labelFMO->setText(QCoreApplication::translate("MainWindow", "FMO", nullptr));
        label_7->setText(QCoreApplication::translate("MainWindow", "Frequency [Hz]", nullptr));
        label_8->setText(QCoreApplication::translate("MainWindow", "Frequency [Hz]", nullptr));
        label_9->setText(QCoreApplication::translate("MainWindow", "Frequency [Hz]", nullptr));
        cb_ssta1->setText(QCoreApplication::translate("MainWindow", "UserL-", nullptr));
        cb_ssta2->setText(QCoreApplication::translate("MainWindow", "UserR-", nullptr));
        cb_ssta3->setText(QCoreApplication::translate("MainWindow", "UserL+", nullptr));
        cb_ssta7->setText(QCoreApplication::translate("MainWindow", "External", nullptr));
        cb_ssta4->setText(QCoreApplication::translate("MainWindow", "Instrument", nullptr));
        cb_ssta5->setText(QCoreApplication::translate("MainWindow", "Keyboard", nullptr));
        cb_ssta0->setText(QCoreApplication::translate("MainWindow", "UserR+", nullptr));
        cb_ssta6->setText(QCoreApplication::translate("MainWindow", "Notes", nullptr));
        cb_psta1->setText(QString());
        cb_psta2->setText(QString());
        cb_psta3->setText(QString());
        cb_psta4->setText(QString());
        cb_psta5->setText(QString());
        cb_psta6->setText(QString());
        cb_psta7->setText(QString());
        cb_psta0->setText(QString());
        pB_Mute_StA->setText(QCoreApplication::translate("MainWindow", "Mute", nullptr));
        label_2->setText(QCoreApplication::translate("MainWindow", "PWM", nullptr));
        pB_play_notes->setText(QCoreApplication::translate("MainWindow", "Notes,  \n"
"Instruments", nullptr));
        pBtoggleRecord->setText(QCoreApplication::translate("MainWindow", "Save", nullptr));
        rb_S0->setText(QCoreApplication::translate("MainWindow", "Instrument 0", nullptr));
        rb_S1->setText(QCoreApplication::translate("MainWindow", "Instrument 1", nullptr));
        rb_S2->setText(QCoreApplication::translate("MainWindow", "Inatrument 2", nullptr));
        rb_S3->setText(QCoreApplication::translate("MainWindow", "Instrument 3", nullptr));
        glidefrequency->setText(QCoreApplication::translate("MainWindow", "glide frq.", nullptr));
        pB_Wavedisplay->setText(QString());
        pB_wd_mode->setText(QString());
        label_5->setText(QCoreApplication::translate("MainWindow", "Hall", nullptr));
        pB_Specrum->setText(QCoreApplication::translate("MainWindow", "Spectrum", nullptr));
        wf_vco->setText(QCoreApplication::translate("MainWindow", "TextLabel", nullptr));
        wf_OSC->setText(QCoreApplication::translate("MainWindow", "TextLabel", nullptr));
        wf_fmo->setText(QCoreApplication::translate("MainWindow", "TextLabel", nullptr));
        pb_clear->setText(QCoreApplication::translate("MainWindow", "Clear", nullptr));
        label_3->setText(QCoreApplication::translate("MainWindow", "Beat per measure", nullptr));
        label_10->setText(QCoreApplication::translate("MainWindow", "M a s   t e r", nullptr));
        pB_Mute->setText(QString());
        pB_Rtsp->setText(QCoreApplication::translate("MainWindow", "RTSP", nullptr));
        pB_Save->setText(QCoreApplication::translate("MainWindow", "Save Default", nullptr));
        pBAudioServer->setText(QCoreApplication::translate("MainWindow", "Audio Server", nullptr));
        pb_SDSview->setText(QCoreApplication::translate("MainWindow", "view SDS", nullptr));
        pBGuiExit->setText(QCoreApplication::translate("MainWindow", "GUI EXIT (ESC)", nullptr));
        pBComposer->setText(QCoreApplication::translate("MainWindow", "Composer", nullptr));
        pb_Keyboard->setText(QCoreApplication::translate("MainWindow", "Keyboard", nullptr));
        cb_overwrite->setText(QCoreApplication::translate("MainWindow", "Overwrite", nullptr));
        pB_oscgroup->setText(QString());
        pb_fftmode->setText(QString());
        lb_FMO_LFO->setText(QCoreApplication::translate("MainWindow", "LFO", nullptr));
        lb_VCO_LFO->setText(QCoreApplication::translate("MainWindow", "LFO", nullptr));
        label_6->setText(QCoreApplication::translate("MainWindow", "adjust", nullptr));
        label_13->setText(QCoreApplication::translate("MainWindow", "adjust", nullptr));
        glidefrequency_2->setText(QCoreApplication::translate("MainWindow", "glide vol.", nullptr));
        cB_Combine->setText(QCoreApplication::translate("MainWindow", "Combine", nullptr));
        label_14->setText(QCoreApplication::translate("MainWindow", "Balance", nullptr));
        cb_connect_vcov->setText(QCoreApplication::translate("MainWindow", "connect VCO", nullptr));
        cb_connect_fmov->setText(QCoreApplication::translate("MainWindow", "connect FMO", nullptr));
        cb_connect_oscv->setText(QCoreApplication::translate("MainWindow", "connect VCO", nullptr));
        cb_connect_oscf->setText(QCoreApplication::translate("MainWindow", "connect FMO", nullptr));
        label_15->setText(QCoreApplication::translate("MainWindow", "Volume [%]", nullptr));
        label_16->setText(QCoreApplication::translate("MainWindow", "Volume [%]", nullptr));
        lbl_frqglide_sec->setText(QCoreApplication::translate("MainWindow", "TextLabel", nullptr));
        pBSynthesizer->setText(QCoreApplication::translate("MainWindow", "Instrument", nullptr));
        label_12->setText(QCoreApplication::translate("MainWindow", "0              Volume        100        |   storing             stored    playing", nullptr));
        cb_fsta0->setText(QString());
        cb_fsta1->setText(QString());
        cb_fsta2->setText(QString());
        cb_fsta3->setText(QString());
        cb_fsta4->setText(QString());
        cb_fsta5->setText(QString());
        cb_fsta7->setText(QString());
        cb_fsta6->setText(QString());
        label_17->setText(QCoreApplication::translate("MainWindow", "delay", nullptr));
        pB_ADSR->setText(QCoreApplication::translate("MainWindow", "ADSR", nullptr));
        menuSound_Lab_GUI->setTitle(QCoreApplication::translate("MainWindow", "Sound Lab GUI", nullptr));
        menuIO->setTitle(QCoreApplication::translate("MainWindow", "IO", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
