//@lic

/*  
    Ocean Sound Lab Application Suite (short Ocean-SL)
	Ocean-SL is a c++Project that provides a set of Sound Managing Applications,
	such as Synthesizer, Audioserver, Composer with Graphical UserInterface for
	Linux based Operating Systems, that allows to generate, play and record sound.

    Copyright (C) 2025  Ulrich.Glasmeyer@web.de

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.

@lic*/


/*
 * ShmMixer.h
 *
 *  Created on: Oct 6, 2024
 *      Author: sirius
 *  Know about Audioserver and Synthesizer processes
 *  Provide the sum of all shared stereo data, that is generated by Synthesizers
 *  to the Audioserver
 */

#ifndef RTSP_SHMMIXER_H_
#define RTSP_SHMMIXER_H_

#include <Ocean.h>
#include <data/DataWorld.h>
#include <Logfacility.h>

class ShmMixer_class : virtual Logfacility_class
{
	string className = "";
public:
	Dataworld_class* 	DaTA_p;
	int 				error = 0;

	void InitShm();
	void AddShm();
	ShmMixer_class( Dataworld_class* data ) :
		Logfacility_class( "ShmMixer_class" )
	{
		DaTA_p = data;
		className = Logfacility_class::className;
//		Set_Loglevel( DEBUG, true);

	};
	virtual ~ShmMixer_class()
	{};
private:

};


#endif /* RTSP_SHMMIXER_H_ */
