/**************************************************************************
MIT License

Copyright (c) 2025 Ulrich Glasmeyer

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
****************************************************************************/

/*
 * ShmMixer.h
 *
 *  Created on: Oct 6, 2024
 *      Author: sirius
 *  Know about Audioserver and Synthesizer processes
 *  Provide the sum of all shared stereo data, that is generated by Synthesizers
 *  to the Audioserver
 */

#ifndef RTSP_SHMMIXER_H_
#define RTSP_SHMMIXER_H_

#include <Ocean.h>
#include <data/DataWorld.h>
#include <Logfacility.h>

class ShmMixer_class : virtual Logfacility_class
{
	string className = "";
public:
	Dataworld_class* 	DaTA_p;
	int 				error = 0;

	void InitShm();
	void AddShm();
	ShmMixer_class( Dataworld_class* data ) :
		Logfacility_class( "ShmMixer_class" )
	{
		DaTA_p = data;
		className = Logfacility_class::className;
//		Set_Loglevel( DEBUG, true);

	};
	virtual ~ShmMixer_class()
	{};
private:

};


#endif /* RTSP_SHMMIXER_H_ */
