/*
 * ShmMixer.h
 *
 *  Created on: Oct 6, 2024
 *      Author: sirius
 *  Know about Audioserver and Synthesizer processes
 *  Provide the sum of all shared stereo data, that is generated by Synthesizers
 *  to the Audioserver
 */

#ifndef RTSP_SHMMIXER_H_
#define RTSP_SHMMIXER_H_

#include <Ocean.h>
#include <data/DataWorld.h>
#include <Logfacility.h>

class ShmMixer_class : virtual Logfacility_class
{
	string className = "";
public:
	Dataworld_class* 	DaTA_p;
	int 				error = 0;

	void InitShm();
	void AddShm();
	ShmMixer_class( Dataworld_class* data ) :
		Logfacility_class( "ShmMixer_class" )
	{
		DaTA_p = data;
		className = Logfacility_class::className;
//		Set_Loglevel( DEBUG, true);

	};
	virtual ~ShmMixer_class()
	{};
private:

};


#endif /* RTSP_SHMMIXER_H_ */
