/*
 * keys.h
 *
 *  Created on: Apr 1, 2024
 *      Author: sirius
 */

/*
https://en.wikipedia.org/wiki/ASCII#Character_set
 */


#ifndef INCLUDE_KEYS_H_
#define INCLUDE_KEYS_H_


enum {
	NULLKEY = 0,

	// OSC frequency
	MAINFREQUENCYKEY,
	VCOFREQUENCYKEY,
	FMOFREQUENCYKEY,

	// OSC volume
	VCOAMPKEY,
	FMOAMPKEY,
	MASTERAMP_KEY,
	MASTERAMP_LOOP_KEY,	 // parameter, LOOP_end, LOOP_step
	MASTERAMP_MUTE_KEY,

	// OSC connect
	CONNECTVCOFMOKEY,
	CONNECTFMOVCOKEY,

	// OSC Waveform
	SETWAVEFORMFMOKEY,
	SETWAVEFORMVCOKEY,
	SETWAVEFORMMAINKEY,

	// Reset OSC
	RESETFMOKEY,
	RESETVCOKEY,
	RESETMAINKEY,

	// ADSR
	ADSR_KEY,
	PMWDIALKEY,
	SOFTFREQUENCYKEY,

	// DataArray
	STORESOUNDKEY,
	STOPRECORD_KEY,
	SETMBAMPPLAYKEY,
	MUTEMBKEY,
	MUTEREC_KEY,
	TOGGLEMBPLAYKEY,
	CLEAR_KEY,
	EXTERNAL_AMPLOOP_KEY,

	// Notes
	NEWNOTESLINEKEY,
	NEWNOTESLINEFLAG,
	UPDATENOTELINEKEY,
	UPDATENOTESKEY,
	NOTESONKEY,
	NOTESOFFKEY,
	PLAYNOTESREC_ON_KEY,
	PLAYNOTESRECOFF_KEY,
	SETNOTESPERSEC_KEY,
	SETBASEOCTAVE_KEY,
	NOTESSTR_KEY,
	UPDATE_NLP_KEY,

	// Wavedisplay
	WAVEDISPLAYTYPEKEY,
	SETWAVEDISPLAYKEY,

	// External
	SAVE_EXTERNALWAVFILEKEY,
	RECORDWAVFILEFLAG,
	READ_EXTERNALWAVEFILE,
	WAVEFILESTR_KEY,
	OTHERSTR_KEY,

	// Instrument
	SAVEINSTRUMENTKEY,
	NEWINSTRUMENTKEY,
	NEWINSTRUMENTFLAG,
	SETINSTRUMENTKEY,
	INSTRUMENTSTR_KEY,

	// Spectrum
	UPDATESPECTRUM_KEY,
	GETSPECTRUM_KEY,

	USERINTERFACE_FLAG,
	EXITKEY
};

#include <vector>

const std::vector<char> init_keys =
{
		// avoid toggle commands here
		SETINSTRUMENTKEY,
		ADSR_KEY,
		PMWDIALKEY,
		SOFTFREQUENCYKEY,
		WAVEDISPLAYTYPEKEY,
		SETWAVEDISPLAYKEY,
		UPDATENOTESKEY,
		SETMBAMPPLAYKEY
};


#endif /* INCLUDE_KEYS_H__ */
