/*
 * keys.h
 *
 *  Created on: Apr 1, 2024
 *      Author: sirius
 */

/*
https://en.wikipedia.org/wiki/ASCII#Character_set
 */


#ifndef INCLUDE_KEYS_H_
#define INCLUDE_KEYS_H_


enum {
	// OSC frequency
	MAINFREQUENCYKEY,
	VCOFREQUENCYKEY,
	FMOFREQUENCYKEY,

	// OSC volume
	MUTEMAINAMP_KEY,
	UNMUTEMAINAMP_KEY,
	VCOAMPKEY,
	FMOAMPKEY,
	MASTER_AMP_KEY,
	MAIN_AMPLOOP_KEY,	 // parameter, LOOP_end, LOOP_step

	// OSC connect
	CONNECTVCOFMOKEY,
	CONNECTFMOVCOKEY,

	// OSC Waveform
	SETWAVEFORMFMOKEY,
	SETWAVEFORMVCOKEY,
	SETWAVEFORMMAINKEY,

	// Reset OSC
	RESETFMOKEY,
	RESETVCOKEY,
	RESETMAINKEY,

	// ADSR
	ADSRDURATIONKEY,
	ADSRDECAYKEY,
	ADSRSUSTAINKEY,
	ADSRHALLKEY,
	PMWDIALKEY,
	SOFTFREQUENCYKEY,

	// DataArray
	STORESOUNDKEY,
	STOPRECORD_KEY,
	SETMBAMPPLAYKEY,
	MUTEMBKEY,
	MUTEREC_KEY,
	TOGGLEMBPLAYKEY,
	CLEAR_KEY,
	EXTERNAL_AMPLOOP_KEY,

	// Notes
	NEWNOTESLINEKEY,
	NEWNOTESLINEFLAG,
	UPDATENOTELINEKEY,
	UPDATENOTESKEY,
	NOTESONKEY,
	NOTESOFFKEY,
	PLAYNOTESREC_ON_KEY,
	PLAYNOTESRECOFF_KEY,
	SETNOTESPERSEC_KEY,
	SETBASEOCTAVE_KEY,

	// Wavedisplay
	WAVEDISPLAYTYPEKEY,
	SETWAVEDISPLAYKEY,

	// External
	RECORDWAVFILEKEY,
	RECORDWAVFILEFLAG,
	SETEXTERNALWAVEFILE,

	// Instrument
	SAVEINSTRUMENTKEY,
	NEWINSTRUMENTKEY,
	NEWINSTRUMENTFLAG,
	SETINSTRUMENTKEY,

	// Spectrum
	UPDATESPECTRUM_KEY,
	GETSPECTRUM_KEY,

	USERINTERFACE_FLAG,
	EXITKEY,
	NULLKEY
};

#include <vector>

const std::vector<char> init_keys = {

		SETINSTRUMENTKEY,
		ADSRDURATIONKEY,
		ADSRDECAYKEY,
		ADSRSUSTAINKEY,
		ADSRHALLKEY,
		PMWDIALKEY,
		SOFTFREQUENCYKEY,
		WAVEDISPLAYTYPEKEY,
		SETWAVEDISPLAYKEY,
		UPDATENOTESKEY
};


#endif /* INCLUDE_KEYS_H__ */
